spring.application.name=demo
server.port=${PORT:8080}
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_SOURCE_USERNAME}
spring.datasource.password=${DATA_SOURCE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.servlet.context-path=/api/v1
spring.security.jwt.secretKey=${JWT_SECRET}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ahmedgarci146@gmail.com
spring.mail.password=fjvnekojmhxtqldv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=
spring.security.privateKey=${PRIVATE_KEY}
spring.security.publicKey=${PUBLIC_KEY}

spring.config.import=optional:classpath:application-env.properties
config.frontEndUrl=${FRONT_END_URL}